---
# Persistent Volume Claim para OpenSearch
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# Deployment para OpenSearch
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
spec:
  replicas: 2
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
      - name: opensearch
        image: opensearchproject/opensearch:latest
        ports:
        - containerPort: 9200
        - containerPort: 9300
        env:
        - name: discovery.seed_hosts
          value: "opensearch"
        - name: cluster.initial_master_nodes
          value: "opensearch-0,opensearch-1"
        - name: cluster.name
          value: "opensearch-cluster"
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - mountPath: /usr/share/opensearch/data
          name: opensearch-data
      volumes:
      - name: opensearch-data
        persistentVolumeClaim:
          claimName: opensearch-pvc
---
# Service para OpenSearch
apiVersion: v1
kind: Service
metadata:
  name: opensearch
spec:
  type: LoadBalancer
  ports:
    - port: 9200
      targetPort: 9200
    - port: 9300
      targetPort: 9300
  selector:
    app: opensearch
---
# Deployment para OpenSearch Dashboards
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch-dashboards
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch-dashboards
  template:
    metadata:
      labels:
        app: opensearch-dashboards
    spec:
      containers:
      - name: opensearch-dashboards
        image: opensearchproject/opensearch-dashboards:latest
        ports:
        - containerPort: 5601
        env:
        - name: OPENSEARCH_HOSTS
          value: "http://opensearch:9200"
---
# Service para OpenSearch Dashboards
apiVersion: v1
kind: Service
metadata:
  name: opensearch-dashboards
spec:
  type: LoadBalancer
  ports:
    - port: 5601
      targetPort: 5601
  selector:
    app: opensearch-dashboards