apiVersion: v1
kind: Service
metadata:
  name: memcached-headless
  labels:
    app: memcached
spec:
  clusterIP: None  # Servicio headless
  selector:
    app: memcached
  ports:
    - name: memcached
      port: 11211
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memcached
spec:
  replicas: 3  # Número de réplicas
  selector:
    matchLabels:
      app: memcached
  serviceName: memcached-headless
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
        - name: memcached
          image: memcached:latest
          ports:
            - containerPort: 11211
              name: memcached
          args:
            - "-m"
            - "32"  # Memoria en MB para cada réplica
            - "-c"
            - "1024"  # Conexiones máximas
          resources:
            requests:
              memory: "64Mi"
              cpu: "20m"
            limits:
              memory: "256Mi"
              cpu: "200m"
  volumeClaimTemplates:
  - metadata:
      name: memcached-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi