version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"  # Management UI
      - "5671:5671"    # SSL port
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./certs:/etc/rabbitmq/certs
      - ./init_rabbitmq.sh:/docker-entrypoint-initdb.d/init_rabbitmq.sh
    environment:
      RABBITMQ_ERLANG_COOKIE: "mysecretcookie"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"