apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: rabbitmq
data:
  enabled_plugins: |
    [rabbitmq_management,rabbitmq_peer_discovery_k8s].
  rabbitmq.conf: |
    listeners.ssl.default = 5671
    ssl_options.cacertfile = /etc/rabbitmq/certs/rabbitmq.crt
    ssl_options.certfile   = /etc/rabbitmq/certs/rabbitmq.crt
    ssl_options.keyfile    = /etc/rabbitmq/certs/rabbitmq.key
    ssl_options.verify     = verify_none
    ssl_options.fail_if_no_peer_cert = false
    management.ssl.port       = 15671
    management.ssl.cacertfile = /etc/rabbitmq/certs/rabbitmq.crt
    management.ssl.certfile   = /etc/rabbitmq/certs/rabbitmq.crt
    management.ssl.keyfile    = /etc/rabbitmq/certs/rabbitmq.key
    management.ssl.verify     = verify_none
    cluster_formation.peer_discovery_backend = rabbit_peer_discovery_k8s
    cluster_formation.k8s.host = kubernetes.default.svc
    cluster_formation.k8s.address_type = hostname
    cluster_partition_handling = autoheal
    queue_master_locator = min-masters